robbert-vdh/nih-plug

- src/wrapper/util.rs
Looks like these were missed in https://github.com/robbert-vdh/nih-plug/commit/7d3beb174e59773cfa676267e4eb9e51c7085222 and https://github.com/robbert-vdh/nih-plug/commit/d878fd692a0a7e3a26c97d29daeec791be5c2436.
> Fix compilation errors when SSE not available

- nih_plug_xtask/src/lib.rs
Hi, thanks to develop this project!
I tried to create a plugin with `nih-plug` and I've found that `nih_plug_xtask` failed to find my plugin project because `nih_plug_xtask` opens its own directory.
I fixed it by replacing `env!` with `std::env::var` to get `CARGO_MANIFEST_DIR` in runtime rather than compile time.
> [nih_plug_xtask] Fix chdir_workspace_root()

- nih_plug_xtask/src/lib.rs
[here](https://github.com/robbert-vdh/nih-plug/blob/f7bfbb8d9553fc2ae72fdfa1e0f23583a36d52ff/nih_plug_xtask/src/lib.rs#L49) it is written as `Architecture::AArch64`, but [later down in the code](https://github.com/robbert-vdh/nih-plug/blob/f7bfbb8d9553fc2ae72fdfa1e0f23583a36d52ff/nih_plug_xtask/src/lib.rs#L423) it uses `Architecture::ARM64` which doesn't exist, failing the build when building on/for an Apple silicon mac.
> fix typoed AArch64 as ARM64

- nih_plug_xtask/src/lib.rs
The current code expects the workspace to be exactly one directory level above the plugin crate. This instead searches upward until it finds a plausible workspace directory, allowing crates to be in e.g. a single `components` directory in my case.
> Make xtask search for workspace more robust

- README.md
Fixes couple of small README typo I noticed when reading.
(Discovered the project via https://old.reddit.com/r/rust/comments/x49m4m/media_clockwork_simple_midi_note_repeater_plugin/.)
> Small typo fixes.

- src/wrapper/vst3/util.rs
Running the [VST3 SDK Validator](https://github.com/steinbergmedia/vst3_public_sdk/tree/55d7ed3c6a25496b41fc4440aaad4fae1b967d37/samples/vst-hosting/validator) for the `midi_inverter` plugin shows one failing test:
[Scan Parameters]
Info:  ===Scan Parameters ====================================
Info:  This component exports 2080 parameter(s)
Info:     Parameter 000 (id=2147481569): [title="MIDI Ch. 1 CC 0"] [unit=""] [type = F, default = 0.000000, unit = 0]
Info:     Parameter 001 (id=2147481570): [title="MIDI Ch. 1 CC 1"] [unit=""] [type = F, default = 0.000000, unit = 0]
Info:     Parameter 002 (id=2147481571): [title="MIDI Ch. 1 CC 2"] [unit=""] [type = F, default = 0.000000, unit = 0]
[...]
Info:     Parameter 2077 (id=2147483646): [title="MIDI Ch. 16 CC 127"] [unit=""] [type = F, …
> Fix off-by-1 error in VST3 parameter range

- Cargo.lock
- nih_plug_derive/Cargo.toml
- nih_plug_derive/src/params.rs
- nih_plug_derive/tests/params.rs
This resolves issue #43. Nested parameters that are **not grouped** are now inserted to the parameter list according to definition order. Grouped parameters remain at the bottom of the parameter list.
> Preserve the order of non-grouped nested parameters

- nih_plug_xtask/src/lib.rs
I noticed some typos and have corrected them.  
- Fixed some typos in comments
- Fixed a typo in an error message
which are separated into two separate commits.
> Fix some typos

- src/formatters.rs
My plugin using the panning formatter failed clap-validator and I noticed there's a bug where it only strips L, not C or R so conversion fails with those values.
> s2v_f32_panning() now strips C and R, not just L

- src/midi.rs
I noticed that I couln't read the channel of a NoteEvent without matching all the enum values, and thought it might be useful since there are already helpers for timing and voice_id (and well, I needed it :)).
I didn't find any contribution guideline, let me know if it's not the right way to do it.
Cheers!
> Add a channel getter to the NoteEvent implementation

- Cargo.lock
- Cargo.toml
- src/event_loop/background_thread.rs
- src/wrapper/clap.rs
- src/wrapper/util.rs
This PR fixes some a few issues MIRI reported when I ran the example `gain` plugin in Clack's host test suite:
* Update the `anymap` dependency: the `0.12.x` version on crates.io is unsound and performs unaligned writes, which are triggered in NIH-plug's CLAP wrapper when initializing the background thread. This PR updates it to the latest beta which doesn't use `unsafe` anymore.
* Fix the `get_factory` method only returning borrowing the inner `clap_plugin_factory` instead of the whole factory struct, which caused untagged access errors.
* Disable FTZ when running under MIRI. This isn't an error, just an unsupported operation in MIRI.
> Various MIRI fixes

- src/wrapper/clap.rs
The macro definition of `nih_export_clap` is missing an explicit module path for `std::sync::Arc` which causes a compilation failure if the invocation site doesn't have `std::sync::Arc` in scope.
> Added explicit module path in nih_export_clap.

- src/formatters.rs
- src/midi.rs
- src/params.rs
- src/params/float.rs
- src/params/smoothing.rs
- src/wrapper/clap/context.rs
- src/wrapper/clap/descriptor.rs
- src/wrapper/standalone/context.rs
- src/wrapper/state.rs
- src/wrapper/vst3/util.rs
- src/wrapper/vst3/view.rs
Hello!
Courtesy of `clippy::doc_markdown`, here is a collection of what I hope are fairly uncontroversial tweaks to the docs: adding/removing backticks for visual consistency. 😅 
I left all mentions of `SysEx` alone because I see that they are consistently unticked and it's more of a concept than an explicit keyword (currently just an example plugin's name), but I could add those too if that's desired?
> Fix backticks in doc comments

- src/params/float.rs
- src/params/integer.rs
This allows calling code e.g. pass a bunch of IntParams to a function that creates widgets - removing the need to create custom widgets for each GUI library and instead use some glue code to generate widgets since now they can determine the correct bounds for a knob/slider from the &IntParam
I'm open to modifying it to return &Range instead of Range... over to you on that API decision
> Added IntParam::range() and FloatParam::range()

- nih_plug_xtask/src/lib.rs
This pr add initial compilation support for RISC V 64.
Tested on `riscv64 qemu user` and `Sophgo Mango rv64imafdc`
> Add initial compile support for RISC V

- Cargo.lock
- Cargo.toml
- nih_plug_egui/Cargo.toml
- nih_plug_egui/src/editor.rs
- nih_plug_egui/src/lib.rs
- nih_plug_egui/src/widgets/generic_ui.rs
- nih_plug_egui/src/widgets/param_slider.rs
- nih_plug_egui/src/widgets/util.rs
- plugins/examples/gain_gui_egui/src/lib.rs
updated to use the latest version of egui and egui_baseview
> update egui and egui_baseview

- CHANGELOG.md
- nih_plug_egui/Cargo.toml
I didn't realize that mouse cursor support in baseview is currently only implemented for Linux. This commit fixes a panic when trying to set the mouse cursor in MacOS or Windows.
> fix panic when setting mouse cursor in nih_plug_egui

- src/wrapper/standalone/backend/cpal.rs
This is trying to solve the same thing as #104.
nih-plug `master` gives distorted audio for me when using wasapi or alsa backends when built standalone.
#104 fixes this, but for me it only worked for one channel, while this worked for all channels.
Tested working on Windows/WASAPI and Linux/Alsa. Further testing would be good too.
> Fix CPAL buffer bug (standalone)

- nih_plug_vizia/src/widgets/param_slider.rs
In cases like a modulation amount slider that has the same negative and positive range, you might want the default value to be non zero, so your user gets some modulation when they open your plugin for the first time.
At the same time, you want them to draw starting from the mid point, and not from the default value. 
I have minimal comments, and I'm not sure about the name.
I wanted to get your feedback first.
PS: my editor wouldn't let me commit before I fixed the typo...  ¯\\\_(ツ)\_/¯
> add new ParamSliderStyle::FromMidPoint

- Cargo.lock
- Cargo.toml
- src/wrapper/clap/context.rs
- src/wrapper/clap/wrapper.rs
Upstream clap-sys at https://github.com/micahrj/clap-sys seems to have accepted pull requests from https://github.com/robbert-vdh/clap-sys and updated the version of CLAP supported.
It appears as though https://github.com/robbert-vdh/clap-sys is no longer required.
Pinned dependency to upstream clap-sys v0.5.0 which supports CLAP 1.2.2.
Minor edits for some extensions which were stabilized between CLAP 1.1.8 and CLAP 1.2.2.
> Use upstream clap-sys, CLAP 1.2.2

- Cargo.lock
- Cargo.toml
- plugins/examples/byo_gui_gl/Cargo.toml
- plugins/examples/byo_gui_gl/src/lib.rs
- plugins/examples/byo_gui_gl/src/main.rs
- plugins/examples/byo_gui_softbuffer/Cargo.toml
- plugins/examples/byo_gui_softbuffer/src/lib.rs
- plugins/examples/byo_gui_softbuffer/src/main.rs
- plugins/examples/byo_gui_wgpu/Cargo.toml
- plugins/examples/byo_gui_wgpu/src/lib.rs
- plugins/examples/byo_gui_wgpu/src/main.rs
Since someone was asking how to use their own custom GUI toolkit using WGPU in nih-plug, I decided to go ahead and create these examples since I have experience doing this in my own baseview shim crates.
These examples include one using OpenGL, one using WGPU, and one using Softbuffer.
> Add "bring your own gui" example plugins

- src/params/smoothing.rs
- src/wrapper/util.rs
Resolved warning: use of deprecated function std::arch::x86_64::_MM_GET_FLUSH_ZERO_MODE
Issue #220
Issue Link: https://github.com/robbert-vdh/nih-plug/issues/220
> Fix for Issue #220
